export const menProductsData = [
  {
    id: "01",
    tag: "NEW",
    img: "/men/men-01.png",
    name: "Air Jordan 1 Mid",
    price: 2349000,
    categories: "Men, Shoes, Clothing",
    type: "Air Jordan",
  },
  {
    id: "02",
    tag: "SALE",
    img: "/men/men-02.png",
    name: "Air Jordan 4 Retro",
    price: 1799000,
    categories: "Men, Shoes, Clothing",
    type: "Air Jordan",
  },
  {
    id: "03",
    tag: "",
    img: "/men/men-03.png",
    name: "Nike Air Monarch III",
    price: 2579000,
    categories: "Men, Shoes, Clothing",
    type: "Air Monarch",
  },
  {
    id: "04",
    tag: "",
    img: "/men/men-04.png",
    name: "Nike Air Monarch IV",
    price: 1999000,
    categories: "Men, Shoes, Clothing",
    type: "Air Monarch",
  },
  {
    id: "05",
    tag: "SALE",
    img: "/men/men-05.png",
    name: "Air Jordan 11 Retro",
    price: 1459000,
    categories: "Men, Shoes, Clothing",
    type: "Air Jordan",
  },
  {
    id: "06",
    tag: "",
    img: "/men/men-06.png",
    name: "Nike Air Monarch V",
    price: 1579000,
    categories: "Men, Shoes, Clothing",
    type: "Air Monarch",
  },
  {
    id: "07",
    tag: "HOT",
    img: "/men/men-jordan.png",
    name: "Air Jordan 11",
    price: 3899000,
    categories: "Men, Shoes, Clothing",
    type: "Air Jordan",
  },
  {
    id: "08",
    tag: "",
    img: "/men/men-monarch.png",
    name: "Nike Air Monarch IV",
    price: 1149000,
    categories: "Men, Shoes, Clothing",
    type: "Air Monarch",
  },
];
